# Generated by Django 4.1.5 on 2023-01-20 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_datetime', models.DateTimeField(default=datetime.datetime.today)),
                ('violation_route', models.CharField(max_length=255)),
                ('violation_county', models.CharField(max_length=255)),
                ('violation_city', models.CharField(max_length=255)),
                ('contact_type', models.CharField(max_length=255)),
                ('oln_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AL', max_length=255)),
                ('oln', models.IntegerField(default=0)),
                ('oln_class', models.CharField(choices=[('EDL', "Enhanced Driver's License"), ('DPC', 'Driver Privilege Card'), ('CDL', "Commercial Driver's License"), ('NDR', 'Non-Driver Identification')], default='EDL', max_length=3)),
                ('cdl', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('violator_name', models.CharField(max_length=255)),
                ('violator_dob', models.DateField(default=datetime.date.today)),
                ('violator_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('violator_hair', models.CharField(choices=[('BR', 'Brown'), ('BL', 'Black'), ('AU', 'Auburn'), ('RE', 'Red'), ('BL', 'Blonde'), ('GR', 'Gray'), ('WH', 'White')], default='BR', max_length=2)),
                ('violator_eyes', models.CharField(choices=[('BR', 'Brown'), ('BL', 'Black'), ('AU', 'Auburn'), ('RE', 'Red'), ('BL', 'Blonde'), ('GR', 'Gray'), ('WH', 'White')], default='BR', max_length=2)),
                ('violator_height', models.CharField(max_length=255)),
                ('violator_address', models.CharField(max_length=255)),
                ('violator_city', models.CharField(max_length=255)),
                ('violator_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AL', max_length=2)),
                ('violator_phone', models.IntegerField()),
                ('violator_email', models.EmailField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_vin', models.CharField(max_length=255)),
                ('vehicle_color', models.CharField(max_length=255)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_make', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('factor_crash', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_passenger', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_spanish', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_car_cam', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_body_cam', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_school_zone', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_construction', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('factor_workers', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('violation_0', models.CharField(choices=[('FTA', 'Failed to aid'), ('UNSF', 'Unsafe start from parked, stopped, standing')], default='FTA', max_length=255)),
                ('violation_1', models.CharField(choices=[('FTA', 'Failed to aid'), ('UNSF', 'Unsafe start from parked, stopped, standing')], default='FTA', max_length=255)),
                ('violation_2', models.CharField(choices=[('FTA', 'Failed to aid'), ('UNSF', 'Unsafe start from parked, stopped, standing')], default='FTA', max_length=255)),
                ('violation_3', models.CharField(choices=[('FTA', 'Failed to aid'), ('UNSF', 'Unsafe start from parked, stopped, standing')], default='FTA', max_length=255)),
                ('violation_4', models.CharField(choices=[('FTA', 'Failed to aid'), ('UNSF', 'Unsafe start from parked, stopped, standing')], default='FTA', max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('issued_datetime', models.DateTimeField(default=datetime.datetime.today)),
                ('court', models.CharField(max_length=255)),
                ('court_appearance_date', models.DateTimeField(default=datetime.datetime.today)),
                ('violator_signature', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
