# Generated by Django 4.1.5 on 2023-01-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('citation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.officer'),
        ),
    ]
