# Generated by Django 4.1.5 on 2023-01-21 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='violator_dob',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
