# Generated by Django 4.1.5 on 2023-01-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='officer',
            new_name='clerk',
        ),
    ]
