# Generated by Django 4.1.5 on 2023-01-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='vehicle_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citation',
            name='violator_phone',
            field=models.IntegerField(),
        ),
    ]
