# Generated by Django 4.1.5 on 2023-01-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0003_alter_citation_vehicle_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='violator_signature',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
