# Generated by Django 4.1.5 on 2023-01-19 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='clerk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
