# Generated by Django 4.1.5 on 2023-01-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clerk_last_login_alter_clerk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerk',
            name='last_login',
        ),
    ]
